# Generated by Django 4.0.3 on 2022-03-18 05:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import famsafe.current_user


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('famsafe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='user',
            field=models.ForeignKey(default=famsafe.current_user.get_current_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
