# Generated by Django 4.0.3 on 2022-04-08 20:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('famsafe', '0004_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='usertable',
        ),
        migrations.DeleteModel(
            name='files',
        ),
    ]
