# Generated by Django 4.0.3 on 2022-04-08 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('famsafe', '0005_rename_user_usertable_delete_files'),
    ]

    operations = [
        migrations.DeleteModel(
            name='usertable',
        ),
    ]
